import Provider from '@components/provider'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RoomLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    // <html lang="en">
    // <body className={inter.className}>
    <Provider>{children}</Provider>
    // </body>
    // </html>
  )
}
