version: '3.8'
services:
  builder:
    build:
      context: .
      dockerfile: ./Dockerfile.socket.prod
      target: builder
    image: poker.ipm/socket:latest
    volumes:
      - $PWD/socket:/socket
      - $PWD/webapp:/webapp
    env_file:
      - ./socket/.env.production 
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.socket.prod
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: poker.ipm/socket:latest
    volumes:
      - $PWD/socket:/socket
    env_file:
      - ./socket/.env.production  
    ports:
      - '5000:5000'
  webapp:
    build:
      context: .
      dockerfile: ./Dockerfile.next.prod
      args:
        - http_proxy
        - https_proxy
        - no_proxy
      env_file:
        - ./webapp/.env.local
    image: poker.ipm/next:latest
    volumes:
      - $PWD/webapp:/webapp 
    ports:
      - '3000:3000'

volumes:
  socket:
  webapp:
