import LoginWithGoogleLink from '@components/login-with-google-link'
import Provider from '@components/provider'
import authOptions from '@lib/auth-options'
import { getServerSession } from 'next-auth'
import Link from 'next/link'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function ({ children }: { children: React.ReactNode }) {
  const session = (await getServerSession(authOptions)) as
    | { user?: User }
    | undefined
  return (
    <Provider>
      <main className="flex flex-col p-4 md:p-24">
        <nav className="flex gap-4">
          <Link className="hover:text-blue-600" href="/" title="Home">
            Home
          </Link>
          <LoginWithGoogleLink
            className="hover:text-red-500 hover:cursor-pointer mb-4 text-right"
            session={session}
          />
        </nav>
        {children}
      </main>
    </Provider>
  )
}
